# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/desjare/src/grumpyplayer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/desjare/src/grumpyplayer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/desjare/src/grumpyplayer/CMakeFiles /home/desjare/src/grumpyplayer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/desjare/src/grumpyplayer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grumpyplayer

# Build rule for target.
grumpyplayer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grumpyplayer
.PHONY : grumpyplayer

# fast build rule for target.
grumpyplayer/fast:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/build
.PHONY : grumpyplayer/fast

audiodevice.o: audiodevice.cpp.o

.PHONY : audiodevice.o

# target to build an object file
audiodevice.cpp.o:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/audiodevice.cpp.o
.PHONY : audiodevice.cpp.o

audiodevice.i: audiodevice.cpp.i

.PHONY : audiodevice.i

# target to preprocess a source file
audiodevice.cpp.i:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/audiodevice.cpp.i
.PHONY : audiodevice.cpp.i

audiodevice.s: audiodevice.cpp.s

.PHONY : audiodevice.s

# target to generate assembly for a file
audiodevice.cpp.s:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/audiodevice.cpp.s
.PHONY : audiodevice.cpp.s

gui.o: gui.cpp.o

.PHONY : gui.o

# target to build an object file
gui.cpp.o:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/gui.cpp.o
.PHONY : gui.cpp.o

gui.i: gui.cpp.i

.PHONY : gui.i

# target to preprocess a source file
gui.cpp.i:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/gui.cpp.i
.PHONY : gui.cpp.i

gui.s: gui.cpp.s

.PHONY : gui.s

# target to generate assembly for a file
gui.cpp.s:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/gui.cpp.s
.PHONY : gui.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/main.cpp.s
.PHONY : main.cpp.s

mediadecoder.o: mediadecoder.cpp.o

.PHONY : mediadecoder.o

# target to build an object file
mediadecoder.cpp.o:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/mediadecoder.cpp.o
.PHONY : mediadecoder.cpp.o

mediadecoder.i: mediadecoder.cpp.i

.PHONY : mediadecoder.i

# target to preprocess a source file
mediadecoder.cpp.i:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/mediadecoder.cpp.i
.PHONY : mediadecoder.cpp.i

mediadecoder.s: mediadecoder.cpp.s

.PHONY : mediadecoder.s

# target to generate assembly for a file
mediadecoder.cpp.s:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/mediadecoder.cpp.s
.PHONY : mediadecoder.cpp.s

player.o: player.cpp.o

.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i

.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s

.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/player.cpp.s
.PHONY : player.cpp.s

videodevice.o: videodevice.cpp.o

.PHONY : videodevice.o

# target to build an object file
videodevice.cpp.o:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/videodevice.cpp.o
.PHONY : videodevice.cpp.o

videodevice.i: videodevice.cpp.i

.PHONY : videodevice.i

# target to preprocess a source file
videodevice.cpp.i:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/videodevice.cpp.i
.PHONY : videodevice.cpp.i

videodevice.s: videodevice.cpp.s

.PHONY : videodevice.s

# target to generate assembly for a file
videodevice.cpp.s:
	$(MAKE) -f CMakeFiles/grumpyplayer.dir/build.make CMakeFiles/grumpyplayer.dir/videodevice.cpp.s
.PHONY : videodevice.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... grumpyplayer"
	@echo "... edit_cache"
	@echo "... audiodevice.o"
	@echo "... audiodevice.i"
	@echo "... audiodevice.s"
	@echo "... gui.o"
	@echo "... gui.i"
	@echo "... gui.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mediadecoder.o"
	@echo "... mediadecoder.i"
	@echo "... mediadecoder.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... videodevice.o"
	@echo "... videodevice.i"
	@echo "... videodevice.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

